update tasker_profile
set
name = $2,
email = $3,
phone = $4,
location = $5,
about = $6,
mounting = $7,
mountingHourly = $8,
delivery = $9,
deliveryHourly = $10,
yard = $11,
yardHourly = $12,
home = $13,
homeHourly = $14,
moving = $15,
movingHourly= $16,
pet = $17,
petHourly = $18,
furniture = $19,
furnitureHourly = $20,
cleaning = $21,
cleaningHourly = $22,
cooking = $23,
cookingHourly = $24,
where tasker_id = $1